### ISSUE TITLE
Deployment Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-curriculum/phase-4-deploying-rails-react-to-heroku#4]
I hit this error during lecture and helped a couple students who also had the issue. It seems to be a problem with [Node v. 17 and Open SSL](https://medium.com/the-node-js-collection/node-js-17-is-here-8dba1e14e382#5f07)
The fix that we applied was to set engines.node in the package.json file at the root of the project to match the version of node I was using to develop locally. Given that this has happened to a few students at this point, it may be worth addressing it in the README here when we discuss the package.json file.

**Comment by ihollander** [comment]
Thanks! I'll take a look. Since odd-numbered Node releases aren't stable, we're more likely to see issues with Node 17 than 16.
