### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by JoeSpizz** [learn-co-curriculum/phase-4-deploying-rails-react-to-heroku#6]
### Canvas Link

https://learning.flatironschool.com/courses/5303/pages/deploying-a-rails-react-app-to-heroku?module_item_id=399074

### Concern

Why is this still in the curriculum? Heroku is dead. 

### Suggested Changes

Replace this with suggestions of what we're supposed to use instead now!

**Comment by lizbur10** [comment]
Hi @JoeSpizz - we are in the process of rewriting the lessons now. They should be updated soon. Apologies for the inconvenience.

**Comment by JoeSpizz** [comment]
That is great news! Is there a preview of what new hosting/deploying
service is suggested?
